name: Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    name: Run Security Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit semgrep

    - name: Run pip-audit
      run: pip-audit

    - name: Run Semgrep
      run: semgrep scan --config "p/default"

    - name: Secret Scanning with Gitleaks
      uses: zricethezav/gitleaks-action@v2.3.4